# coding = utf8
# 五言绝句：j5
# 七言绝句：j7

poems = {
    '登鸛雀樓': {
        'type_id': 'j5',
        'type': '五言絕句',
        'title': '登鸛雀樓',
        'author': '王之渙',
        'content': '白日依山盡，黃河入海流。欲窮千里目，更上一層樓。',  # pushButton.setText('白')
        'sounds': [
            '白[baak6]',
            '日[jat6]',
            '依[ji1]',
            '山[saan1]',
            '盡[zeon6]',
            '登鶴雀樓-1',
            '黃[wong4]',
            '河[ho4]',
            '入[jap6]',
            '海[hoi2]',
            '流[lau4]',
            '登鶴雀樓-2',
            '欲[juk6]',
            '窮[kung4]',
            '千[cin1]',
            '里[lei5]',
            '目[muk6]',
            '登鶴雀樓-3',
            '更[gang3]',
            '上[soeng5]',
            '一[jat1]',
            '層[cang4]',
            '樓[lau4]',
            '登鶴雀樓-4'
        ]
    },
    '靜夜思': {
        'type_id': 'j5',
        'type': '五言絕句',
        'title': '靜夜思',
        'author': '李白',
        'content': '床前明月光，疑似地上霜。舉頭望明月，低頭思故鄉。',
        'sound': [
            '床[cong4]',
            '前[cin4]',
            '明[ming4]',
            '月[jyut6]',
            '光[gwong1]',
            '靜夜思-1',
            '疑[ji4]',
            '似[si6]',
            '地[dei6]',
            '上[soeng6]',
            '霜[soeng1]',
            '靜夜思-2',
            '舉[geoi2]',
            '頭[tau4]',
            '望[mong6]',
            '明[ming4]',
            '月[jyut6]',
            '靜夜思-3',
            '低[dai1]',
            '頭[tau4]',
            '思[si1]',
            '故[gu3]',
            '鄉[hoeng1]',
            '靜夜思-4'
        ]
    },
    '涼州詞': {
        'type_id': 'j7',
        'type': '七言絕句',
        'title': '涼州詞',
        'author': '王翰',
        'content': '葡萄美酒夜光杯，欲飲琵琶馬上催。醉臥沙場君莫笑，古來征戰幾人回。',
        'sounds': [
             '葡[pou4]',
             '萄[tou4]',
             '美[mei5]',
             '酒[zau2]',
             '夜[je6]',
             '光[gwong1]',
             '杯[bui1]',
             '涼州詞-1',
             '欲[juk6]',
             '飲[jam2]',
             '琵[pei4]',
             '琶[paa4]',
             '馬[maa5]',
             '上[soeng6]',
             '催[ceoi1]',
             '涼州詞-2',
             '醉[zeoi3]',
             '臥[ngo6]',
             '沙[saa1]',
             '場[coeng4]',
             '君[gwan1]',
             '莫[mok6]',
             '笑[siu3]',
             '涼州詞-3',
             '古[gu2]',
             '來[loi4]',
             '征[zing1]',
             '戰[zin3]',
             '幾[gei2]',
             '人[jan4]',
             '回[wui4]',
             '涼州詞-4'
        ]
    },
    '春曉': {
        'type_id': 'j5',
        'type': '五言絕句',
        'title': '春曉',
        'author': '孟浩然',
        'content': '春眠不覺曉，處處聞啼鳥。夜來風雨聲，花落知多少。',
        'sounds': [
             '春[ceon1]',
             '眠[min4]',
             '不[bat1]',
             '覺[gok3/gaau3]',
             '曉[hiu2]',
             '處[cyu5]',
             '處[cyu5]',
             '聞[man4]',
             '啼[tai4]',
             '鳥[niu5]',
             '夜[je6/je2]',
             '來[loi4]',
             '風[fung1]',
             '雨[jyu5]',
             '聲[seng1]',
             '花[faa1]',
             '落[lok6]',
             '知[zi1]',
             '多[do1]',
             '少[siu2]'
        ]
    }
}

page_id = {
    'j5': 0,
    'j7': 1,
    'l5': 2,
    'l7': 3,
}